### ISSUE TITLE
where can  get this file wannier90_hr_to_3NN.dat

### ISSUE THREAD

**Issue by zcbz** [coherent17/physical_modeling_DFT#1]

**Comment by coherent17** [comment]
Hi zcbc,

This is my course project, the data is currently lost now, sorry for that. But I remember the data are come from VASP.

Thanks

**Comment by zcbz** [comment]
Hi coherent17,
Is this code a wannier function, or a eigenvalue?
Thanks

**Comment by coherent17** [comment]
Eigenvalue, just try to visualize some result from VASP

**Comment by zcbz** [comment]
Ok, you are so nice!
